import Body from "./Body" 

export async function generateMetadata({  }) {
  return {
    title: 'Create Next App',
  	description: 'Generated by create next app',
  }
}

export default function Home() {
  return (
    <>
      <Body />
		</>
  )
}
